apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mist-pod
  name: mist-pod
spec:
  containers:
  - image: polenoso/mist-server-ubuntu:1.0
    name: mist-pod
    ports:
        - containerPort: 8080
          hostPort: 8080
        - containerPort: 4242
          hostPort: 4242
        - containerPort: 1935
          hostPort: 1935
    volumeMounts:
        - mountPath: /video
          name: videos
        - name: dshm
          mountPath: /dev/shm
    resources: {}
    stdin: true
    tty: true
  volumes:
    - hostPath:
       path: /videos
       type: Directory
      name: videos
    - name: dshm
      emptyDir:
        medium: Memory
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  hostNetwork: true
status: {}
